[wordpress]
listen = /var/run/sockets/php-fpm.sock
listen.mode = 0600

pm = ondemand
pm.max_children = 5
pm.process_idle_timeout = 10s
pm.max_requests = 4000
pm.status_path = /status

ping.path = /ping
ping.response = pong

catch_workers_output = yes
decorate_workers_output = no
clear_env = no

php_admin_value[upload_tmp_dir] = /var/www/tmp
php_admin_value[session.save_path] = /var/www/tmp
php_admin_value[upload_max_filesize] = 256M
php_admin_value[post_max_size] = 256M
php_admin_value[max_execution_time] = 300
php_admin_value[max_input_time] = 120
php_admin_value[max_input_vars] = 10000
php_admin_value[display_errors] = Off
php_admin_value[open_basedir] = /var/www/html:/var/www/tmp:/tmp:/usr/share:/run/secrets
php_admin_value[disable_functions] = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_setpriority,exec,system,passthru,shell_exec,proc_open,popen,show_source,highlight_file,symlink,link,dl,posix_kill,posix_setuid,posix_getpwuid

env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /var/www/tmp
env[TMPDIR] = /var/www/tmp
env[TEMP] = /var/www/tmp
