port 0
unixsocket /var/run/sockets/valkey.sock
unixsocketperm 700

dir /tmp

maxmemory 64mb
maxmemory-policy allkeys-lru

save ""
appendonly no

protected-mode yes
timeout 0
tcp-keepalive 0

loglevel warning
syslog-enabled no

databases 16
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
